SUPABASE_URL = "your_url"
SUPABASE_KEY = "your_key"
WOO_URL = "https://servicepack.ro"
WOO_CONSUMER_KEY = "ck_2d1b49057730eb2af511f6bc19a9d45e57f21d05"
WOO_CONSUMER_SECRET = "cs_53bca735aac15d246c6816c503d750615a65a93d"
